### ISSUE TITLE
HL_NUM_NODES=1 HL_PP=2 HL_TP=4 HL_DP=1 scripts/run_llama13b.sh command is stuck

### ISSUE THREAD

**Issue by tileintel** [HabanaAI/Model-References#37]
Hi, 
I am running Model-References branch 1.12.0. I tried to follow instructions from https://github.com/HabanaAI/Model-References/tree/master/PyTorch/nlp/DeepSpeedExamples/Megatron-DeepSpeed to run `LLaMA 13B on 8 HPUs with BF16 precision`. 
Specifically, I run the following command:
`HL_DATA_DIR_ROOT=PATH_TO_MY_DATASET HL_NUM_NODES=1 HL_PP=2 HL_TP=4 HL_DP=1 scripts/run_llama13b.sh`
Unfortunately, the process is stuck. I pasted here the log printed on the console: 
```> setting tensorboard ...
_initialize_distributed: Initializing with below params:
args.local_rank: 7
args.world_size: 8
args.rank: 7
args.distributed_backend: hccl
hccl device_count:  8
[2023-12-07 09:08:03,644] [WARNING] [comm.py:163:init_deepspeed_backend] HCCL backend in DeepSpeed not yet implemented
[2023-12-07 09:08:03,644] [INFO] [comm.py:637:init_distributed] cdb=None
> initializing tensor model parallel with size 4
> initializing pipeline model parallel with size 2
> setting random seeds to 1234 ...
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
============================= HABANA PT BRIDGE CONFIGURATION ===========================
 PT_HPU_LAZY_MODE = 1
 PT_RECIPE_CACHE_PATH =
 PT_CACHE_FOLDER_DELETE = 0
 PT_HPU_RECIPE_CACHE_CONFIG =
 PT_HPU_MAX_COMPOUND_OP_SIZE = 9223372036854775807
 PT_HPU_LAZY_ACC_PAR_MODE = 0
 PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES = 0
---------------------------: System Configuration :---------------------------
Num CPU Cores : 160
CPU RAM       : 1056389528 KB
------------------------------------------------------------------------------
> compiling dataset index builder ...
make: Entering directory '/mnt/nvme2n1/Model-References/PyTorch/nlp/DeepSpeedExamples/Megatron-DeepSpeed/megatron/data'
make: Nothing to be done for 'default'.
make: Leaving directory '/mnt/nvme2n1/Model-References/PyTorch/nlp/DeepSpeedExamples/Megatron-DeepSpeed/megatron/data'
>>> done with dataset index builder. Compilation time: 0.095 seconds
WARNING: constraints for invoking optimized fused softmax kernel are not met. We default back to unfused kernel invocations.
> compiling and loading fused kernels ...
>>> done with compiling and loading fused kernels. Compilation time: 0.005 seconds
``` 
It is stuck here forever. After taking a closer look, the following code from megatron/training.py is stuck:
```
start_time_tensor = torch.FloatTensor([_TRAIN_START_TIME]).to(get_current_device())
torch.distributed.all_reduce(start_time_tensor,
                                 op=torch.distributed.ReduceOp.MIN,
                                 async_op=args.use_hpu
                                 )
```
Look like all get_current_device() always return 0, so torch.distributed.all_reduce was stuck because of all of processed were assigned to one device hpu:0.
Can anyone please tell me how to overcome this?
Thanks

**Comment by tileintel** [comment]
It turns out that there was something wrong with drivers. I just restarted drivers and restarted network, and all work.
